name = "Ohata"
uuid = "a8c67e1a-51a8-4393-8cc1-c530063cb104"
authors = ["Leticia-maria <leticiam@andrew.cmu.edu> and contributors"]
version = "0.1.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
SpecialFunctions = "2"
julia = "^1.6.7"
TimerOutputs = "^0.5.0"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
documenter = ["Documenter"]
test = ["Test"]
